### ISSUE TITLE
Spaces in profile name in URL

### ISSUE THREAD

**Issue by dbluhm** [decentralized-identity/didcomm-demo#39]
A space in the profile name will cause a space in the fragment in the URL.

**Comment by frostyfrog** [comment]
On my end, the spaces are converted to a %20 and the page still works as expected upon refresh. Are you experiencing something different?

**Comment by dbluhm** [comment]
Refresh still works but the space persists in the fragment on Firefox (at least visually, maybe it's a sneaky percent encoded value but I don't think so).

**Comment by dbluhm** [comment]
Maybe it's best to resolve this by just implementing #34?

**Comment by frostyfrog** [comment]
Quite possibly. On Chrome, it's showing the %20 in place of the space. Either way though, the fragment isn't sent to the server, so whether or not it shows up from a technical perspective doesn't matter. The only issue this will cause (as far as I know) is when someone copies and pastes the URL into something like Slack or Discord and the respective platforms don't convert the whole thing to a link.

I recommend that we fix this by implementing #34

**Comment by dbluhm** [comment]
Closing as a non-issue; let's focus on #34
