### ISSUE TITLE
Trim off message when linking to 'unknown' message types for the link.

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/didcomm-demo#54]

**Comment by TelegramSam** [comment]
This will avoid the problem (for now) with DIDComm.org and the poor message formatting.
Example: `https://didcomm.org/trust-ping/2.0/ping-response` should display the same thing, but link to `https://didcomm.org/trust-ping/2.0/` in order to get the rendering to work better. This is not invalid, and we can correct it later when we update the main site.

**Comment by frostyfrog** [comment]
This should've been resolved a couple days ago via this commit. Is it still not working? (the URL should show the full message, but it should link to the protocol)
https://github.com/decentralized-identity/didcomm-demo/commit/81353743db8b43d8f375b6bdf9abe6be7d07eb3e

**Comment by dbluhm** [comment]
Actually, just spotted a bug:
![image](https://github.com/decentralized-identity/didcomm-demo/assets/22032832/691a8d7a-1744-41dd-81ea-8f9aa892723c)

The feature disclosure links are getting their version lobbed off the end as a result of the changes from the last PR. @frostyfrog

**Comment by frostyfrog** [comment]
K, I'll take a look at what's going on there

**Comment by TelegramSam** [comment]
the place I spotted it was in the left list after receiving a message of unknown type.
