### ISSUE TITLE
Is the demo broken for some reason?

### ISSUE THREAD

**Issue by SuryaSHalwasia** [decentralized-identity/didcomm-demo#70]
I am unable to get the did of the participants. It shows an error in the console.
<img width="335" alt="didcomm_demo" src="https://github.com/decentralized-identity/didcomm-demo/assets/118595736/c176a142-b985-4a10-ab57-a1d8f990633c">
Thanks

**Comment by dbluhm** [comment]
This is a problem related to the DID of the mediator used by default. We're investigating! Thanks for the report.

**Comment by dbluhm** [comment]
If you refresh (with cache clearing), https://demo.didcomm.org should be working again :slightly_smiling_face:
